# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.11.dev1+gcdd87b6.d20230527'
__version_tuple__ = version_tuple = (0, 1, 11, 'dev1', 'gcdd87b6.d20230527')
