# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.11.dev0+g4d7c81d.d20230527'
__version_tuple__ = version_tuple = (0, 1, 11, 'dev0', 'g4d7c81d.d20230527')
