# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.11.dev6+gf4a2724.d20230530'
__version_tuple__ = version_tuple = (0, 1, 11, 'dev6', 'gf4a2724.d20230530')
